### PR TITLE
Customize protocol index pages

### PR DESCRIPTION
**Pull request by eshaben**
This customizes the index pages in the protocol section a little bit. This was kinda tough as I wasn't sure of what external links I should add to some of these sections. I think the lines between some of these pages and the wiki are blurry and maybe something we need to revisit.

⚠️ PR should be reviewed with mkdocs branch set to `eshaben/index-pages`

### CODE REVIEW

**Comment by nhussein11** [comment]
For some weird reason, I'm getting the following error while reviewing this PR:
@eshaben @dawnkelly09, any idea what might be happening here?

image

**Review by nhussein11 — DISMISSED** [review]
LGTM!

**Review by nhussein11 — APPROVED** [review]
LGTM!

**Review by themacexpert — APPROVED** [review]
LGTM!

**Review by nhussein11 — APPROVED** [review]
LGTM!

**Pull request merged**
