### PR TITLE
[FIX] - Removing duplicated input elements on termynal snippets

### PR DESCRIPTION
**Pull request by nhussein11**
This PR removes duplicate input elements in the Termynal code snippets of the "Install Dependencies for the Polkadot SDK"

### CODE REVIEW

**Review by eshaben — APPROVED** [review]
LGTM!

**Review by 0xLucca — CHANGES_REQUESTED** [review]
The `Add Trusted Nodes` page was broken by this changes
image

**Comment by nhussein11** [comment]
@0xLucca Leading spaces were automatically modified by prettier, shall we turn it off? @eshaben

**Review by 0xLucca — COMMENTED** [review]
I think we should remove it for HTML files maybe

**Comment by nhussein11** [comment]
Mmm, actually, I don't like the idea of removing .html files from Prettier since IMO it's important to have every single piece of code (or html/CSS) standardized and formatted

I think that initially, this add trusted nodes code snippets should have been written using `<pre>` tags for example, to avoid this formatting conflict

**Comment by eshaben** [comment]
Let me take a closer look

**Review by 0xLucca — APPROVED** [review]
LGTM!

**Review by eshaben — APPROVED** [review]
🚀

**Pull request merged**
